### ISSUE TITLE
CSS not being applied when using @sortableLink directive

### ISSUE THREAD

**Issue by TechhDan** [s-damian/larasort#1]
I'm looking at the CSS and I see the CSS will only be applied when using the CSS class ```.with-larasort```. Looking over the documentation i don't see that you mention that this class must manually be added. Do i have to manually add this class to the table? I followed the steps in the documentation but the CSS is not being applied. 

![image](https://user-images.githubusercontent.com/11691784/189737555-69705287-f05f-4e9c-bbca-f97a5efe2dfe.png)

**Comment by s-damian** [comment]
Hello.

You must put the CSS class `with-larasort` on a HTML tag which encloses the blade directive (on the table or thead tag by example).

I just added it in the documentation, in the "Basic usage" part.

I forgot to write this in the doc. Thank you for reporting it to me.
