### ISSUE TITLE
Incompatibility with Laravel 9 Scout

### ISSUE THREAD

**Issue by TechhDan** [s-damian/larasort#2]
Is there any chance you might be able to add support for use with Laravel 9 [Scout](https://laravel.com/docs/9.x/scout). The trait ```Laravel\Scout\Searchable``` is not compatible with the ```SDamian\Larasort\AutoSortable``` trait. Sorting works fine when clicking on columns. However, If I search on a model that's using Scout it breaks.

In case this is better suited to be fixed on Scout's repo I've opened up a [feature request](https://github.com/laravel/scout/issues/649) there as well.

![image](https://user-images.githubusercontent.com/11691784/189771289-8ab11e34-9121-49ca-8e5a-c9d55c820086.png)

```
"require": {
        "php": "^8.0.2",
        "guzzlehttp/guzzle": "^7.2",
        "laravel/framework": "^9.19",
        "laravel/sanctum": "^3.0",
        "laravel/scout": "^9.4",
        "laravel/tinker": "^2.7",
        "laravel/ui": "^4.0",
        "s-damian/larasort": "^1.0"
    },
    "require-dev": {
        "fakerphp/faker": "^1.9.1",
        "laravel/pint": "^1.0",
        "laravel/sail": "^1.0.1",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^6.1",
        "phpunit/phpunit": "^9.5.10",
        "spatie/laravel-ignition": "^1.0"
    },
```

**Comment by s-damian** [comment]
I don't know Laravel Scout. But for your models where you use Laravel Scout, you can use [LarasortManual](https://github.com/s-damian/larasort#larasortmanual---for-without-eloquent-orm)

**Comment by TechhDan** [comment]
Thanks I'll look into that.
